change to alpine base images

diff --git a/psql-app/scripts/start-services b/psql-app/scripts/start-services
--- a/psql-app/scripts/start-services
+++ b/psql-app/scripts/start-services
@@ -1,10 +1,4 @@
 #!/bin/bash
-# Postgres Backend: Run script
-#
-#  Copyright (c) 2021-2022 Cisco Systems, Inc. and others.  All rights reserved.
-#
-# Author: Tim Evens <tim@evensweb.com>
-#
 
 # Postgres details - Can be set using docker -e
 export POSTGRES_USER=${POSTGRES_USER:="openbmp"}
@@ -14,52 +8,43 @@ export POSTGRES_PORT=${POSTGRES_PORT:="5432"}
 export POSTGRES_DB=${POSTGRES_DB:="openbmp"}
 export POSTGRES_SSL_ENABLE=${POSTGRES_SSL_ENABLE:="true"}
 export POSTGRES_SSL_MODE=${POSTGRES_SSL_MODE:="require"}
-export MEM=${MEM:="1"}                          # mem in gigabytes
+export MEM=${MEM:="1"}
 export PGCONNECT_TIMEOUT=15
 
-# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-# Functions
-# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 
-# -----------------------------------------------
-# Check Kafka to make sure it's valid
-# -----------------------------------------------
 check_kafka() {
     echo "===> Performing Kafka check"
 
     if [[ ${KAFKA_FQDN:-""} == "" ]]; then
-       echo "ERROR: Missing ENV KAFKA_FQDN.  Cannot proceed until you add that in docker run -e KAFKA_FQDN=<...>"
+       echo "ERROR: Missing ENV KAFKA_FQDN. Cannot proceed until you add that in docker run -e KAFKA_FQDN=<...>"
        exit 1
-
     fi
 
     echo "===> Checking Kafka bootstrap server connection"
-    kafkacat -u -b $KAFKA_FQDN -L | grep broker
+    kcat -u -b $KAFKA_FQDN -L | grep broker
 
     if [[ $? -ne 0 ]]; then
         echo "ERROR: Failed to connect to Kafka at $KAFKA_FQDN, check the docker run -e KAFKA_FQDN= value"
         exit 1
     fi
 
-    echo "testing" | timeout 5 kafkacat -b $KAFKA_FQDN -P -t openbmp.parsed.test
+    echo "testing" | timeout 5 kcat -b $KAFKA_FQDN -P -t openbmp.parsed.test
     echo "===> Checking if we can successfully consume messages"
-    timeout 5 kafkacat -u -b $KAFKA_FQDN -C -c 1 -o beginning -t openbmp.parsed.test > /dev/null
+    timeout 5 kcat -u -b $KAFKA_FQDN -C -c 1 -o beginning -t openbmp.parsed.test > /dev/null
 
     if [[ $? -ne 0 ]]; then
         echo "ERROR: Failed to connect to Kafka broker, check the Kafka 'advertised.listeners' configuration."
-        echo "       Advertised hostname must be reachable within the container. You can run this container"
-        echo "       with --add-host <hostname>:<ip> to map the ip address within the container."
-        echo "       You can also add/update the persistent /config/hosts file with the broker hostname/ip."
         exit 1
     fi
 }
 
-# -----------------------------------------------
-# Configure Postgres shell profile
-# -----------------------------------------------
+# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+# Configure
+# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+
+
 config_postgres_profile() {
     echo "===> Configuring PostgreSQL Shell Profile"
-
     echo "export PGUSER=$POSTGRES_USER" > /usr/local/openbmp/pg_profile
     echo "export PGPASSWORD=$POSTGRES_PASSWORD" >> /usr/local/openbmp/pg_profile
     echo "export PGHOST=$POSTGRES_HOST" >> /usr/local/openbmp/pg_profile
@@ -67,54 +52,46 @@ config_postgres_profile() {
     echo "export PGDATABASE=$POSTGRES_DB" >> /usr/local/openbmp/pg_profile
 }
 
-# -----------------------------------------------
-# Initdb Postgres
-# -----------------------------------------------
-initdb_postgres() {
-    if [[ ! -f /config/do_not_init_db ]]; then
-      echo " ===> Initializing the DB"
 
-      echo "Waiting for postgres to start..."
-      done=0
-      while [  $done -eq 0 ]; do
-          psql -c "select 1;" > /dev/null 2>&1
-          if [[ $? -ne 0 ]]; then
-             echo "    postgres not running, sleeping for 20 seconds..."
-             sleep 20
-          else
-              done=1
-              break
-          fi
-      done
-
-      # Load the schema files
-      echo " ===> Loading Schemas"
-
-      echo "------" > /var/log/db_schema_load.log
-      for file in $(ls -v /usr/local/openbmp/database/*.sql); do
-        echo " ===[ $file ] ========================================" >> /var/log/db_schema_load.log
-        psql < $file >> /var/log/db_schema_load.log  2>&1
-      done
-
-      touch /config/do_not_init_db
-    fi
-}
-
-# -----------------------------------------------
-# Update hosts file
-# -----------------------------------------------
 update_hosts() {
     echo "===> Updating /etc/hosts"
-
-    # Update the etc hosts file
     if [[ -f /config/hosts ]]; then
         cat /config/hosts >> /etc/hosts
     fi
 }
 
-# -----------------------------------------------
-# Enable RPKI
-# -----------------------------------------------
+# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+# Functions
+# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+
+
+initdb_postgres() {
+    if [[ ! -f /config/do_not_init_db ]]; then
+        echo " ===> Initializing the DB"
+        echo "Waiting for postgres to start..."
+        done=0
+        while [  $done -eq 0 ]; do
+            psql -c "select 1;" > /dev/null 2>&1
+            if [[ $? -ne 0 ]]; then
+                echo "    postgres not running, sleeping for 20 seconds..."
+                sleep 20
+            else
+                done=1
+                break
+            fi
+        done
+
+        echo " ===> Loading Schemas"
+        echo "------" > /var/log/db_schema_load.log
+        for file in $(ls -v /usr/local/openbmp/database/*.sql); do
+            echo " ===[ $file ] ========================================" >> /var/log/db_schema_load.log
+            psql < $file >> /var/log/db_schema_load.log  2>&1
+        done
+        touch /config/do_not_init_db
+    fi
+}
+
+
 enable_rpki() {
     echo "===> Enabling RPKI"
 
@@ -128,9 +105,7 @@ SETVAR
 
 }
 
-# -----------------------------------------------
-# Enable DB-IP import
-# -----------------------------------------------
+
 enable_dbip() {
     echo "===> Enabling DB-IP Import"
 
@@ -143,13 +118,10 @@ SETVAR
 
     # Load DB-IP on start
     echo "Running DB-IP Import"
-   /usr/local/openbmp/db-ip-import.sh 2>/var/log/cron-dbip-import.log > /var/log/cron-dbip-import.log &
+   /usr/local/openbmp/db-ip-import.sh 2>/var/log/cron-dbip-import.log > /var/log/cron-dbip-import.log
 }
 
 
-# -----------------------------------------------
-# Enable IRR
-# -----------------------------------------------
 enable_irr() {
     echo "===> Enabling IRR"
 
@@ -163,12 +135,10 @@ SETVAR
 
     # Load IRR data
     echo "Loading IRR data"
-    /usr/local/openbmp/gen_whois_route.py -u $PGUSER -p $PGPASSWORD $PGHOST  2>/var/log/irr_load.log  > /var/log/irr_load.log &
+    /usr/local/openbmp/gen_whois_route.py -u $PGUSER -p $PGPASSWORD $PGHOST  2>/var/log/irr_load.log  > /var/log/irr_load.log
 }
 
-# -----------------------------------------------
-# config_cron
-# -----------------------------------------------
+
 config_cron() {
     cat > /etc/cron.d/openbmp <<SETVAR
 MAILTO=""
@@ -200,68 +170,85 @@ SETVAR
 
 }
 
-# -----------------------------------------------
-# Upgrade SQL
-# -----------------------------------------------
+
 upgrade() {
+    if [[ -f /config/do_not_init_db ]]; then
+        if [[ ! -f /config/psql-app-upgraded.2.1.0 ]]; then
+            echo "===> Upgrading to 2.1.0"
+            /tmp/upgrade/upgrade_2.1.0.sh
+            touch /config/psql-app-upgraded.2.1.0
+            echo "===> Done with upgrade"
+        fi
 
-  if [[ -f /config/do_not_init_db ]]; then
+        if [[ ! -f /config/psql-app-upgraded.2.2.0 ]]; then
+            echo "===> Upgrading to 2.2.0"
+            /tmp/upgrade/upgrade_2.2.0.sh
+            touch /config/psql-app-upgraded.2.2.0
+            echo "===> Done with upgrade"
+        fi
 
-    if [[ ! -f /config/psql-app-upgraded.2.1.0 ]]; then
-      echo "===> Upgrading to 2.1.0"
-      /tmp/upgrade/upgrade_2.1.0.sh
-      touch /config/psql-app-upgraded.2.1.0
-      echo "===> Done with upgrade"
+        if [[ ! -f /config/psql-app-upgraded.2.2.1 ]]; then
+            echo "===> Upgrading to 2.2.1"
+            /tmp/upgrade/upgrade_2.2.1.sh
+            touch /config/psql-app-upgraded.2.2.1
+            echo "===> Done with upgrade"
+        fi
+
+        if [[ ! -f /config/psql-app-upgraded.2.2.2 ]]; then
+            echo "===> Upgrading to 2.2.2"
+            /tmp/upgrade/upgrade_2.2.2.sh
+            touch /config/psql-app-upgraded.2.2.2
+            echo "===> Done with upgrade"
+        fi
+    else
+        touch /config/psql-app-upgraded.2.1.0
+        touch /config/psql-app-upgraded.2.2.0
+        touch /config/psql-app-upgraded.2.2.1
+        touch /config/psql-app-upgraded.2.2.2
     fi
-
-    if [[ ! -f /config/psql-app-upgraded.2.2.0 ]]; then
-      echo "===> Upgrading to 2.2.0"
-      /tmp/upgrade/upgrade_2.2.0.sh
-      touch /config/psql-app-upgraded.2.2.0
-      echo "===> Done with upgrade"
-    fi
-
-   if [[ ! -f /config/psql-app-upgraded.2.2.1 ]]; then
-      echo "===> Upgrading to 2.2.1"
-      /tmp/upgrade/upgrade_2.2.1.sh
-      touch /config/psql-app-upgraded.2.2.1
-      echo "===> Done with upgrade"
-    fi
-
-   if [[ ! -f /config/psql-app-upgraded.2.2.2 ]]; then
-      echo "===> Upgrading to 2.2.2"
-      /tmp/upgrade/upgrade_2.2.2.sh
-      touch /config/psql-app-upgraded.2.2.2
-      echo "===> Done with upgrade"
-    fi
-
-  else
-      touch /config/psql-app-upgraded.2.1.0
-      touch /config/psql-app-upgraded.2.2.0
-      touch /config/psql-app-upgraded.2.2.1
-      touch /config/psql-app-upgraded.2.2.2
-  fi
 }
 
 
-# -----------------------------------------------
-# run_consumer
-# -----------------------------------------------
+# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+# Daemons
+# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+start_rsyslog() {
+    while true; do
+        if ! pgrep -x "rsyslogd" > /dev/null; then
+            echo "===> Starting rsyslog service"
+            rsyslogd
+        else
+            echo "===> rsyslog is running"
+        fi
+        sleep 10  # Check every 10 seconds if rsyslog is running
+    done
+}
+
+
+start_cron() {
+    while true; do
+        if ! pgrep -x "crond" > /dev/null; then
+            echo "===> Starting cron service"
+            crond
+        else
+            echo "===> cron is running"
+        fi
+        sleep 10  # Check every 10 seconds if cron is running
+    done
+}
+
+# Start the consumer
 run_consumer() {
     echo "===> Starting consumer"
-
     if [[ ! -f /config/obmp-psql.yml ]]; then
         cd /config
         unzip /usr/local/openbmp/obmp-psql-consumer.jar obmp-psql.yml
-
-
         if [[ ! -f /config/obmp-psql.yml ]]; then
             echo "ERROR: Cannot create /config/obmp-psql.yml"
-            echo "       Update permissions on /config volume to 7777 OR add configuration file to /config volume"
             exit 1
         fi
 
-         # Update configuration
+        # Update configuration
         sed -i -e "s/\([ ]*bootstrap.servers:\)\(.*\)/\1 \"${KAFKA_FQDN}\"/" /config/obmp-psql.yml
         sed -i -e "s/\([ ]*host[ ]*:\)\(.*\)/\1 \"${POSTGRES_HOST}:${POSTGRES_PORT}\"/" /config/obmp-psql.yml
         sed -i -e "s/\([ ]*username[ ]*:\)\(.*\)/\1 \"${POSTGRES_USER}\"/" /config/obmp-psql.yml
@@ -273,7 +260,7 @@ run_consumer() {
 
     heap_mem=${MEM}G
 
-    # Run
+    # Run consumer in background
     cd /var/log
     java -Xmx${heap_mem} -Xms128m -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions \
          -XX:InitiatingHeapOccupancyPercent=30 -XX:G1MixedGCLiveThresholdPercent=30 \
@@ -286,12 +273,12 @@ run_consumer() {
     cd /tmp
 }
 
+
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-# Run
+# Main
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 SYS_NUM_CPU=$(grep processor /proc/cpuinfo | wc -l)
 
-# Clear locks
 if [[ ! -d /tmp/locks ]]; then
   mkdir /tmp/locks
 else
@@ -308,29 +295,30 @@ source /usr/local/openbmp/pg_profile
 
 config_cron
 
+# Enable services based on environment variables
 rm -f /etc/cron.d/openbmp-rpki
 if [[ ${ENABLE_RPKI:-""} != "" && $ENABLE_RPKI == 1 ]]; then
-    enable_rpki
+    enable_rpki &
 fi
 
 rm -f /etc/cron.d/openbmp-irr
 if [[ ${ENABLE_IRR:-""} != "" && $ENABLE_IRR == 1 ]]; then
-    enable_irr
+    enable_irr &
 fi
 
 rm -f /etc/cron.d/openbmp-dbip
 if [[ ${ENABLE_DBIP:-""} != "" && $ENABLE_DBIP == 1 ]]; then
-    enable_dbip
+    enable_dbip &
 fi
-
 
 initdb_postgres
 
-# Get rid of previous rsyslogd pid
 rm -f /var/run/rsyslogd.pid
+rm -f /var/run/crond.pid
 
-service cron start
-service rsyslog start
+start_rsyslog &
+
+start_cron &
 
 upgrade
 
@@ -338,7 +326,8 @@ run_consumer
 
 echo "===> Now running!!!"
 
-while [ 1 ]; do
+# This keeps the container running, and checks if the consumer is still alive.
+while true; do
     sleep 300
     pgrep -f obmp-psql-consumer.jar >/dev/null 2>&1
     if [[ $? != 0 ]]; then
@@ -348,4 +337,3 @@ while [ 1 ]; do
       run_consumer
     fi
 done
-
